export interface City {
  slug: string;
  ar: string;
  fr: string;
  /** الجهة — عندنا غير للمدن الكبار، وماكتّستعملش فالواجهة دابا */
  region?: string;
  /** أسماء دارجة/بديلة للبحث الذكي */
  aliases: string[];
  /** إحداثيات — عندنا غير للمدن الكبار */
  lat?: number;
  lng?: number;
  /** عدد السكان — إحصاء 2024 (المندوبية السامية للتخطيط) */
  population: number;
}

/* ============================================================
   مدن المغرب

   كانو 22 مدينة فقط: اللي كيسكن فبرشيد ولا فأيت ملول ولا
   فالفنيدق ماكانش عندو فين يحط الإعلان ديالو — كيختار أقرب مدينة
   كبيرة، والنتيجة بحث كيكذب على المشتري.

   دابا 220 جماعة حضرية من إحصاء 2024. مرتّبين حسب عدد السكان
   تنازلياً: المدن الكبار فوق فالقائمة (وهي اللي كيختارها الناس
   أكثر)، وحتى محلّل الدارجة كيمشي بهاد الترتيب فكيختار المدينة
   الكبيرة ملي يكون شي اسم مشترك.

   المصدر: db/sources/morocco-cities-2024.xlsx

   ملاحظة: «أولاد حسين» كانت مكرّرة فالمصدر (جوج جماعات بنفس
   الاسم) — جمعناهم فوحدة، ماشي منطقي نوريو للمستخدم نفس الاسم
   جوج مرات وهو مايعرفش أشمن وحدة.

   الجهة والإحداثيات عندنا غير للمدن الكبار — ماكتّستعملوش
   فالواجهة، وماكناش غادي نخترعو 200 إحداثية.
   ============================================================ */
export const CITIES: City[] = [
  { slug: "casablanca", ar: "الدار البيضاء", fr: "Casablanca", region: "الدار البيضاء ـ سطات", aliases: ["كازا", "كازابلانكا", "البيضا", "casa", "casablanca", "dar lbida"], lat: 33.573, lng: -7.59, population: 3215935 },
  { slug: "tanger", ar: "طنجة", fr: "Tanger", region: "طنجة ـ تطوان ـ الحسيمة", aliases: ["طنجة", "طنجا", "tanger", "tanja"], lat: 35.77, lng: -5.8, population: 1275428 },
  { slug: "fes", ar: "فاس", fr: "Fès", region: "فاس ـ مكناس", aliases: ["فاس", "fes", "fès"], lat: 34.03, lng: -5.0, population: 1167842 },
  { slug: "marrakech", ar: "مراكش", fr: "Marrakech", region: "مراكش ـ آسفي", aliases: ["مراكش", "marrakech", "marrakch"], lat: 31.63, lng: -7.99, population: 1002697 },
  { slug: "sale", ar: "سلا", fr: "Salé", region: "الرباط ـ سلا ـ القنيطرة", aliases: ["سلا", "sale", "salé"], lat: 34.05, lng: -6.8, population: 945101 },
  { slug: "meknes", ar: "مكناس", fr: "Meknès", region: "فاس ـ مكناس", aliases: ["مكناس", "meknes"], lat: 33.9, lng: -5.55, population: 551503 },
  { slug: "rabat", ar: "الرباط", fr: "Rabat", region: "الرباط ـ سلا ـ القنيطرة", aliases: ["رباط", "rabat"], lat: 34.02, lng: -6.84, population: 509916 },
  { slug: "kenitra", ar: "القنيطرة", fr: "Kénitra", region: "الرباط ـ سلا ـ القنيطرة", aliases: ["القنيطرة", "قنيطرة", "kenitra"], lat: 34.26, lng: -6.58, population: 507736 },
  { slug: "oujda", ar: "وجدة", fr: "Oujda", region: "الشرق", aliases: ["وجدة", "oujda"], lat: 34.68, lng: -1.9, population: 506224 },
  { slug: "agadir", ar: "أكادير", fr: "Agadir", region: "سوس ـ ماسة", aliases: ["اكادير", "أكادير", "agadir"], lat: 30.42, lng: -9.6, population: 504768 },
  { slug: "tetouan", ar: "تطوان", fr: "Tétouan", region: "طنجة ـ تطوان ـ الحسيمة", aliases: ["تطوان", "tetouan"], lat: 35.57, lng: -5.37, population: 422757 },
  { slug: "safi", ar: "آسفي", fr: "Safi", region: "مراكش ـ آسفي", aliases: ["اسفي", "آسفي", "safi"], lat: 32.3, lng: -9.24, population: 323888 },
  { slug: "dar-bouazza", ar: "دار بوعزة", fr: "Dar Bouazza", aliases: ["دار بوعزة", "dar bouazza"], population: 302970 },
  { slug: "temara", ar: "تمارة", fr: "Témara", region: "الرباط ـ سلا ـ القنيطرة", aliases: ["تمارة", "temara"], lat: 33.93, lng: -6.91, population: 297098 },
  { slug: "laayoune", ar: "العيون", fr: "Laâyoune", region: "العيون ـ الساقية الحمراء", aliases: ["العيون", "laayoune"], lat: 27.15, lng: -13.2, population: 262791 },
  { slug: "el-jadida", ar: "الجديدة", fr: "El Jadida", region: "الدار البيضاء ـ سطات", aliases: ["الجديدة", "jadida"], lat: 33.25, lng: -8.5, population: 237464 },
  { slug: "ait-melloul", ar: "أيت ملول", fr: "Ait Melloul", aliases: ["أيت ملول", "ait melloul"], population: 210870 },
  { slug: "beni-mellal", ar: "بني ملال", fr: "Béni Mellal", region: "بني ملال ـ خنيفرة", aliases: ["بني ملال", "beni mellal"], lat: 32.34, lng: -6.36, population: 209594 },
  { slug: "bouskoura", ar: "بوسكورة", fr: "Bouskoura", aliases: ["بوسكورة", "bouskoura"], population: 200359 },
  { slug: "khouribga", ar: "خريبكة", fr: "Khouribga", region: "بني ملال ـ خنيفرة", aliases: ["خريبكة", "khouribga"], lat: 32.88, lng: -6.9, population: 195931 },
  { slug: "mohammedia", ar: "المحمدية", fr: "Mohammedia", region: "الدار البيضاء ـ سطات", aliases: ["المحمدية", "mohammedia"], lat: 33.69, lng: -7.38, population: 194358 },
  { slug: "settat", ar: "سطات", fr: "Settat", region: "الدار البيضاء ـ سطات", aliases: ["سطات", "settat"], lat: 33.0, lng: -7.62, population: 171556 },
  { slug: "berrechid", ar: "برشيد", fr: "Berrechid", aliases: ["برشيد", "berrechid"], population: 168687 },
  { slug: "dakhla", ar: "الداخلة", fr: "Dakhla", region: "الداخلة ـ وادي الذهب", aliases: ["الداخلة", "dakhla"], lat: 23.68, lng: -15.95, population: 165463 },
  { slug: "nador", ar: "الناظور", fr: "Nador", region: "الشرق", aliases: ["الناظور", "ناظور", "nador"], lat: 35.17, lng: -2.93, population: 158202 },
  { slug: "taza", ar: "تازة", fr: "Taza", aliases: ["تازة", "taza"], population: 150763 },
  { slug: "inezgane", ar: "إنزكان", fr: "Inezgane", aliases: ["إنزكان", "inezgane"], population: 137512 },
  { slug: "larache", ar: "العرائش", fr: "Larache", aliases: ["العرائش", "larache"], population: 133731 },
  { slug: "guelmim", ar: "كلميم", fr: "Guelmim", aliases: ["كلميم", "guelmim"], population: 126729 },
  { slug: "khemisset", ar: "الخميسات", fr: "Khémisset", aliases: ["الخميسات", "khemisset"], population: 125834 },
  { slug: "ksar-el-kebir", ar: "القصر الكبير", fr: "Ksar El Kebir", aliases: ["القصر الكبير", "ksar el kebir"], population: 124701 },
  { slug: "khenifra", ar: "خنيفرة", fr: "Khenifra", aliases: ["خنيفرة", "khenifra"], population: 123738 },
  { slug: "skhirate", ar: "الصخيرات", fr: "Skhirate", aliases: ["الصخيرات", "skhirate"], population: 122705 },
  { slug: "bni-yakhlef", ar: "بني يخلف", fr: "Bni Yakhlef", aliases: ["بني يخلف", "bni yakhlef"], population: 117653 },
  { slug: "sidi-yahya-zaer", ar: "سيدي يحيى زعير", fr: "Sidi Yahya Zaer", aliases: ["سيدي يحيى زعير", "sidi yahya zaer"], population: 116649 },
  { slug: "ben-guerir", ar: "ابن جرير", fr: "Ben Guerir", aliases: ["ابن جرير", "ben guerir"], population: 114872 },
  { slug: "ait-amira", ar: "أيت عميرة", fr: "Ait Amira", aliases: ["أيت عميرة", "ait amira"], population: 113236 },
  { slug: "dcheira-el-jihadia", ar: "الدشيرة الجهادية", fr: "Dcheira El Jihadia", aliases: ["الدشيرة الجهادية", "dcheira el jihadia"], population: 113041 },
  { slug: "ouislane", ar: "ويسلان", fr: "Ouislane", aliases: ["ويسلان", "ouislane"], population: 112180 },
  { slug: "drargua", ar: "الدراركة", fr: "Drargua", aliases: ["الدراركة", "drargua"], population: 107621 },
  { slug: "lqliaa", ar: "القليعة", fr: "Lqliaa", aliases: ["القليعة", "lqliaa"], population: 107133 },
  { slug: "el-kelaa-des-sraghna", ar: "قلعة السراغنة", fr: "El Kelaâ des Sraghna", aliases: ["قلعة السراغنة", "el kelaa des sraghna"], population: 106418 },
  { slug: "tassoultante", ar: "تسلطانت", fr: "Tassoultante", aliases: ["تسلطانت", "tassoultante"], population: 106013 },
  { slug: "harbil", ar: "حربيل", fr: "Harbil", aliases: ["حربيل", "harbil"], population: 105790 },
  { slug: "moulay-abdellah", ar: "مولاي عبد الله", fr: "Moulay Abdellah", aliases: ["مولاي عبد الله", "moulay abdellah"], population: 103993 },
  { slug: "tiflet", ar: "تيفلت", fr: "Tiflet", aliases: ["تيفلت", "tiflet"], population: 103850 },
  { slug: "taourirt", ar: "تاوريرت", fr: "Taourirt", aliases: ["تاوريرت", "taourirt"], population: 100402 },
  { slug: "oulad-teima", ar: "أولاد تايمة", fr: "Oulad Teima", aliases: ["أولاد تايمة", "oulad teima"], population: 100284 },
  { slug: "berkane", ar: "بركان", fr: "Berkane", aliases: ["بركان", "berkane"], population: 99069 },
  { slug: "ain-el-aouda", ar: "عين العودة", fr: "Ain El Aouda", aliases: ["عين العودة", "ain el aouda"], population: 98502 },
  { slug: "ech-challalate", ar: "الشلالات", fr: "Ech-challalate", aliases: ["الشلالات", "ech-challalate", "ech challalate"], population: 98015 },
  { slug: "errachidia", ar: "الرشيدية", fr: "Errachidia", region: "درعة ـ تافيلالت", aliases: ["الرشيدية", "errachidia"], lat: 31.93, lng: -4.42, population: 97687 },
  { slug: "fquih-ben-salah", ar: "الفقيه بن صالح", fr: "Fquih Ben Salah", aliases: ["الفقيه بن صالح", "fquih ben salah"], population: 97380 },
  { slug: "deroua", ar: "الدروة", fr: "Deroua", aliases: ["الدروة", "deroua"], population: 96619 },
  { slug: "martil", ar: "مرتيل", fr: "Martil", aliases: ["مرتيل", "martil"], population: 95896 },
  { slug: "al-majjatia-oulad-taleb", ar: "المجاطية أولاد الطالب", fr: "Al Majjatia Oulad Taleb", aliases: ["المجاطية أولاد الطالب", "al majjatia oulad taleb"], population: 95457 },
  { slug: "sidi-slimane", ar: "سيدي سليمان", fr: "Sidi Slimane", aliases: ["سيدي سليمان", "sidi slimane"], population: 95114 },
  { slug: "oued-zem", ar: "وادي زم", fr: "Oued Zem", aliases: ["وادي زم", "oued zem"], population: 93776 },
  { slug: "saada", ar: "سعادة", fr: "Saada", aliases: ["سعادة", "saada"], population: 91903 },
  { slug: "ain-chkef", ar: "عين الشقف", fr: "Ain Chkef", aliases: ["عين الشقف", "ain chkef"], population: 91541 },
  { slug: "gueznaia", ar: "كزناية", fr: "Gueznaia", aliases: ["كزناية", "gueznaia"], population: 88676 },
  { slug: "lahraouyine", ar: "الهراويين", fr: "Lahraouyine", aliases: ["الهراويين", "lahraouyine"], population: 87977 },
  { slug: "sefrou", ar: "صفرو", fr: "Sefrou", aliases: ["صفرو", "sefrou"], population: 86903 },
  { slug: "tiznit", ar: "تيزنيت", fr: "Tiznit", aliases: ["تيزنيت", "tiznit"], population: 86595 },
  { slug: "taroudannt", ar: "تارودانت", fr: "Taroudannt", aliases: ["تارودانت", "taroudannt"], population: 83496 },
  { slug: "ouad-essafa", ar: "واد الصفا", fr: "Ouad Essafa", aliases: ["واد الصفا", "ouad essafa"], population: 83442 },
  { slug: "essaouira", ar: "الصويرة", fr: "Essaouira", aliases: ["الصويرة", "essaouira"], population: 82962 },
  { slug: "oulad-azzouz", ar: "أولاد عزوز", fr: "Oulad Azzouz", aliases: ["أولاد عزوز", "oulad azzouz"], population: 81048 },
  { slug: "guercif", ar: "جرسيف", fr: "Guercif", aliases: ["جرسيف", "guercif"], population: 80703 },
  { slug: "ouarzazate", ar: "ورزازات", fr: "Ouarzazate", aliases: ["ورزازات", "ouarzazate"], population: 79218 },
  { slug: "fnideq", ar: "الفنيدق", fr: "Fnideq", aliases: ["الفنيدق", "fnideq"], population: 77250 },
  { slug: "sidi-hajjaj-oued-hassar", ar: "سيدي حجاج واد حصار", fr: "Sidi Hajjaj Oued Hassar", aliases: ["سيدي حجاج واد حصار", "sidi hajjaj oued hassar"], population: 76362 },
  { slug: "sidi-taibi", ar: "سيدي الطيبي", fr: "Sidi Taîbi", aliases: ["سيدي الطيبي", "sidi taibi"], population: 76227 },
  { slug: "tan-tan", ar: "طانطان", fr: "Tan Tan", aliases: ["طانطان", "tan tan"], population: 76134 },
  { slug: "ameur", ar: "عامر", fr: "Ameur", aliases: ["عامر", "ameur"], population: 75942 },
  { slug: "sidi-kacem", ar: "سيدي قاسم", fr: "Sidi Kacem", aliases: ["سيدي قاسم", "sidi kacem"], population: 75037 },
  { slug: "had-soualem", ar: "حد السوالم", fr: "Had Soualem", aliases: ["حد السوالم", "had soualem"], population: 74762 },
  { slug: "ain-attig", ar: "عين عتيق", fr: "Ain Attig", aliases: ["عين عتيق", "ain attig"], population: 73985 },
  { slug: "sidi-bibi", ar: "سيدي بيبي", fr: "Sidi Bibi", aliases: ["سيدي بيبي", "sidi bibi"], population: 72929 },
  { slug: "souk-el-arbaa", ar: "سوق الأربعاء", fr: "Souk El Arbaa", aliases: ["سوق الأربعاء", "souk el arbaa"], population: 70894 },
  { slug: "mdiq", ar: "المضيق", fr: "M'diq", aliases: ["المضيق", "mdiq"], population: 67599 },
  { slug: "benslimane", ar: "بن سليمان", fr: "Benslimane", aliases: ["بن سليمان", "benslimane"], population: 67317 },
  { slug: "youssoufia", ar: "اليوسفية", fr: "Youssoufia", aliases: ["اليوسفية", "youssoufia"], population: 65669 },
  { slug: "midelt", ar: "ميدلت", fr: "Midelt", aliases: ["ميدلت", "midelt"], population: 62648 },
  { slug: "ain-harrouda", ar: "عين حرودة", fr: "Ain Harrouda", aliases: ["عين حرودة", "ain harrouda"], population: 60804 },
  { slug: "souk-sebt-ouled-nemma", ar: "سوق السبت أولاد النمة", fr: "Souk Sebt Ouled Nemma", aliases: ["سوق السبت أولاد النمة", "souk sebt ouled nemma"], population: 60293 },
  { slug: "mehdya", ar: "المهدية", fr: "Mehdya", aliases: ["المهدية", "mehdya"], population: 58558 },
  { slug: "ouezzane", ar: "وزان", fr: "Ouezzane", aliases: ["وزان", "ouezzane"], population: 57737 },
  { slug: "azrou", ar: "أزرو", fr: "Azrou", aliases: ["أزرو", "azrou"], population: 57657 },
  { slug: "boujdour", ar: "بوجدور", fr: "Boujdour", aliases: ["بوجدور", "boujdour"], population: 57360 },
  { slug: "ait-ourir", ar: "أيت أورير", fr: "Ait Ourir", aliases: ["أيت أورير", "ait ourir"], population: 56954 },
  { slug: "es-semara", ar: "السمارة", fr: "Es-semara", aliases: ["السمارة", "es-semara", "es semara"], population: 56607 },
  { slug: "oulad-tayeb", ar: "أولاد الطيب", fr: "Oulad Tayeb", aliases: ["أولاد الطيب", "oulad tayeb"], population: 56352 },
  { slug: "sidi-bennour", ar: "سيدي بنور", fr: "Sidi Bennour", aliases: ["سيدي بنور", "sidi bennour"], population: 56201 },
  { slug: "tit-mellil", ar: "تيط مليل", fr: "Tit Mellil", aliases: ["تيط مليل", "tit mellil"], population: 56019 },
  { slug: "bouznika", ar: "بوزنيقة", fr: "Bouznika", aliases: ["بوزنيقة", "bouznika"], population: 55722 },
  { slug: "ben-mansour", ar: "بن منصور", fr: "Ben Mansour", aliases: ["بن منصور", "ben mansour"], population: 53545 },
  { slug: "sidi-mohamed-lahmar", ar: "سيدي محمد لحمر", fr: "Sidi Mohamed Lahmar", aliases: ["سيدي محمد لحمر", "sidi mohamed lahmar"], population: 52679 },
  { slug: "temsia", ar: "تمسية", fr: "Temsia", aliases: ["تمسية", "temsia"], population: 52663 },
  { slug: "oulad-salah", ar: "أولاد صالح", fr: "Oulad Salah", aliases: ["أولاد صالح", "oulad salah"], population: 51621 },
  { slug: "biougra", ar: "بيوكرى", fr: "Biougra", aliases: ["بيوكرى", "biougra"], population: 50626 },
  { slug: "ourika", ar: "أوريكة", fr: "Ourika", aliases: ["أوريكة", "ourika"], population: 50558 },
  { slug: "bni-ansar", ar: "بني أنصار", fr: "Bni Ansar", aliases: ["بني أنصار", "bni ansar"], population: 50508 },
  { slug: "al-hoceima", ar: "الحسيمة", fr: "Al Hoceima", aliases: ["الحسيمة", "al hoceima"], population: 50225 },
  { slug: "laouamra", ar: "العوامرة", fr: "Laouamra", aliases: ["العوامرة", "laouamra"], population: 48253 },
  { slug: "kasba-tadla", ar: "قصبة تادلة", fr: "Kasba Tadla", aliases: ["قصبة تادلة", "kasba tadla"], population: 48172 },
  { slug: "azilal", ar: "أزيلال", fr: "Azilal", aliases: ["أزيلال", "azilal"], population: 48138 },
  { slug: "bejaad", ar: "بجعد", fr: "Bejaad", aliases: ["بجعد", "bejaad"], population: 47209 },
  { slug: "tarmigt", ar: "ترميكت", fr: "Tarmigt", aliases: ["ترميكت", "tarmigt"], population: 46963 },
  { slug: "al-aaroui", ar: "العروي", fr: "Al Aaroui", aliases: ["العروي", "al aaroui"], population: 46540 },
  { slug: "mrirt", ar: "مريرت", fr: "M'rirt", aliases: ["مريرت", "mrirt"], population: 46285 },
  { slug: "chefchaouen", ar: "شفشاون", fr: "Chefchaouen", aliases: ["شفشاون", "chefchaouen"], population: 46168 },
  { slug: "aourir", ar: "أورير", fr: "Aourir", aliases: ["أورير", "aourir"], population: 46032 },
  { slug: "soualem-trifiya", ar: "السوالم الطريفية", fr: "Soualem Trifiya", aliases: ["السوالم الطريفية", "soualem trifiya"], population: 45285 },
  { slug: "bouarg", ar: "بوعرك", fr: "Bouarg", aliases: ["بوعرك", "bouarg"], population: 44626 },
  { slug: "tinghir", ar: "تنغير", fr: "Tinghir", aliases: ["تنغير", "tinghir"], population: 44239 },
  { slug: "sahel-oulad-hriz", ar: "الساحل أولاد احريز", fr: "Sahel Oulad H'riz", aliases: ["الساحل أولاد احريز", "sahel oulad hriz"], population: 43776 },
  { slug: "sidi-bouknadel", ar: "سيدي بوقنادل", fr: "Sidi Bouknadel", aliases: ["سيدي بوقنادل", "sidi bouknadel"], population: 43598 },
  { slug: "sidi-abdellah-ghiat", ar: "سيدي عبد الله غيات", fr: "Sidi Abdellah Ghiat", aliases: ["سيدي عبد الله غيات", "sidi abdellah ghiat"], population: 43237 },
  { slug: "inchaden", ar: "إنشادن", fr: "Inchaden", aliases: ["إنشادن", "inchaden"], population: 42724 },
  { slug: "zagora", ar: "زاكورة", fr: "Zagora", aliases: ["زاكورة", "zagora"], population: 42294 },
  { slug: "azemmour", ar: "أزمور", fr: "Azemmour", aliases: ["أزمور", "azemmour"], population: 42098 },
  { slug: "loudaya", ar: "الودايا", fr: "Loudaya", aliases: ["الودايا", "loudaya"], population: 41761 },
  { slug: "mnasra", ar: "المناصرة", fr: "Mnasra", aliases: ["المناصرة", "mnasra"], population: 41434 },
  { slug: "el-hajeb", ar: "الحاجب", fr: "El Hajeb", aliases: ["الحاجب", "el hajeb"], population: 41359 },
  { slug: "had-boumoussa", ar: "حد بوموسى", fr: "Had Boumoussa", aliases: ["حد بوموسى", "had boumoussa"], population: 41154 },
  { slug: "jerada", ar: "جرادة", fr: "Jerada", aliases: ["جرادة", "jerada"], population: 41014 },
  { slug: "el-aioun-sidi-mellouk", ar: "العيون سيدي ملوك", fr: "El Aioun Sidi Mellouk", aliases: ["العيون سيدي ملوك", "el aioun sidi mellouk"], population: 40652 },
  { slug: "tameslohte", ar: "تامصلوحت", fr: "Tameslohte", aliases: ["تامصلوحت", "tameslohte"], population: 40283 },
  { slug: "houara-oulad-raho", ar: "هوارة أولاد رحو", fr: "Houara Oulad Raho", aliases: ["هوارة أولاد رحو", "houara oulad raho"], population: 39947 },
  { slug: "sidi-yahya-el-gharb", ar: "سيدي يحيى الغرب", fr: "Sidi Yahya El Gharb", aliases: ["سيدي يحيى الغرب", "sidi yahya el gharb"], population: 39946 },
  { slug: "taounate", ar: "تاونات", fr: "Taounate", aliases: ["تاونات", "taounate"], population: 39114 },
  { slug: "bahhara-ouled-ayad", ar: "البحارة أولاد عياد", fr: "Bahhara Ouled Ayad", aliases: ["البحارة أولاد عياد", "bahhara ouled ayad"], population: 38611 },
  { slug: "chichaoua", ar: "شيشاوة", fr: "Chichaoua", aliases: ["شيشاوة", "chichaoua"], population: 38452 },
  { slug: "laattaouia", ar: "العطاوية", fr: "Laattaouia", aliases: ["العطاوية", "laattaouia"], population: 38405 },
  { slug: "sidi-ali-ben-hamdouche", ar: "سيدي علي بن حمدوش", fr: "Sidi Ali Ben Hamdouche", aliases: ["سيدي علي بن حمدوش", "sidi ali ben hamdouche"], population: 38169 },
  { slug: "chtouka", ar: "اشتوكة", fr: "Chtouka", aliases: ["اشتوكة", "chtouka"], population: 38025 },
  { slug: "ameur-seflia", ar: "عامر السفلية", fr: "Ameur Seflia", aliases: ["عامر السفلية", "ameur seflia"], population: 37935 },
  { slug: "alouidane", ar: "العويدان", fr: "Alouidane", aliases: ["العويدان", "alouidane"], population: 37450 },
  { slug: "bradia", ar: "البراديعة", fr: "Bradia", aliases: ["البراديعة", "bradia"], population: 37064 },
  { slug: "belfaa", ar: "بلفاع", fr: "Belfaa", aliases: ["بلفاع", "belfaa"], population: 36774 },
  { slug: "zaio", ar: "زايو", fr: "Zaio", aliases: ["زايو", "zaio"], population: 36766 },
  { slug: "zoumi", ar: "زومي", fr: "Zoumi", aliases: ["زومي", "zoumi"], population: 36573 },
  { slug: "aguelmous", ar: "أكلموس", fr: "Aguelmous", aliases: ["أكلموس", "aguelmous"], population: 36560 },
  { slug: "ouahat-sidi-brahim", ar: "واحة سيدي إبراهيم", fr: "Ouahat Sidi Brahim", aliases: ["واحة سيدي إبراهيم", "ouahat sidi brahim"], population: 36493 },
  { slug: "mograne", ar: "مكران", fr: "Mograne", aliases: ["مكران", "mograne"], population: 36452 },
  { slug: "nouaceur", ar: "النواصر", fr: "Nouaceur", aliases: ["النواصر", "nouaceur"], population: 36326 },
  { slug: "aghouatim", ar: "أغواطيم", fr: "Aghouatim", aliases: ["أغواطيم", "aghouatim"], population: 36258 },
  { slug: "dar-laaslouji", ar: "دار العسلوجي", fr: "Dar Laaslouji", aliases: ["دار العسلوجي", "dar laaslouji"], population: 36072 },
  { slug: "assilah", ar: "أصيلة", fr: "Assilah", aliases: ["أصيلة", "assilah"], population: 36039 },
  { slug: "ouled-hcine", ar: "أولاد حسين", fr: "Ouled Hcine", aliases: ["أولاد حسين", "ouled hcine"], population: 69245 },
  { slug: "haouzia", ar: "الحوزية", fr: "Haouzia", aliases: ["الحوزية", "haouzia"], population: 35777 },
  { slug: "lalla-mimouna", ar: "لالة ميمونة", fr: "Lalla Mimouna", aliases: ["لالة ميمونة", "lalla mimouna"], population: 35600 },
  { slug: "arbaoua", ar: "عرباوة", fr: "Arbaoua", aliases: ["عرباوة", "arbaoua"], population: 35077 },
  { slug: "imzouren", ar: "إمزورن", fr: "Imzouren", aliases: ["إمزورن", "imzouren"], population: 34848 },
  { slug: "laghnadra", ar: "الغنادرة", fr: "Laghnadra", aliases: ["الغنادرة", "laghnadra"], population: 34680 },
  { slug: "sidi-rahal-chatai", ar: "سيدي رحال الشاطئ", fr: "Sidi Rahal Chatai", aliases: ["سيدي رحال الشاطئ", "sidi rahal chatai"], population: 34431 },
  { slug: "sidi-al-kamel", ar: "سيدي الكامل", fr: "Sidi Al Kamel", aliases: ["سيدي الكامل", "sidi al kamel"], population: 34016 },
  { slug: "demnate", ar: "دمنات", fr: "Demnate", aliases: ["دمنات", "demnate"], population: 33635 },
  { slug: "ben-ahmed", ar: "بن أحمد", fr: "Ben Ahmed", aliases: ["بن أحمد", "ben ahmed"], population: 33469 },
  { slug: "oulad-rahmoune", ar: "أولاد رحمون", fr: "Oulad Rahmoune", aliases: ["أولاد رحمون", "oulad rahmoune"], population: 33380 },
  { slug: "ait-faska", ar: "أيت فاسكة", fr: "Ait Faska", aliases: ["أيت فاسكة", "ait faska"], population: 33076 },
  { slug: "ain-taoujdate", ar: "عين تاوجطات", fr: "Ain Taoujdate", aliases: ["عين تاوجطات", "ain taoujdate"], population: 33055 },
  { slug: "kceibya", ar: "القصيبية", fr: "Kceibya", aliases: ["القصيبية", "kceibya"], population: 33007 },
  { slug: "dar-bel-amri", ar: "دار بلعامري", fr: "Dar Bel Amri", aliases: ["دار بلعامري", "dar bel amri"], population: 32873 },
  { slug: "sidi-smail", ar: "سيدي إسماعيل", fr: "Sidi Smail", aliases: ["سيدي إسماعيل", "sidi smail"], population: 32694 },
  { slug: "moulay-bousselham", ar: "مولاي بوسلهام", fr: "Moulay Bousselham", aliases: ["مولاي بوسلهام", "moulay bousselham"], population: 32643 },
  { slug: "mechraa-bel-ksiri", ar: "مشرع بلقصيري", fr: "Mechraa Bel Ksiri", aliases: ["مشرع بلقصيري", "mechraa bel ksiri"], population: 32615 },
  { slug: "souihla", ar: "سويهلة", fr: "Souihla", aliases: ["سويهلة", "souihla"], population: 32506 },
  { slug: "laqsir", ar: "لقصير", fr: "Laqsir", aliases: ["لقصير", "laqsir"], population: 32377 },
  { slug: "jorf-el-melha", ar: "جرف الملحة", fr: "Jorf El Melha", aliases: ["جرف الملحة", "jorf el melha"], population: 31976 },
  { slug: "sidi-slimane-echcharraa", ar: "سيدي سليمان الشراعة", fr: "Sidi Slimane Echcharraa", aliases: ["سيدي سليمان الشراعة", "sidi slimane echcharraa"], population: 31686 },
  { slug: "zeghanghane", ar: "زغنغان", fr: "Zeghanghane", aliases: ["زغنغان", "zeghanghane"], population: 31431 },
  { slug: "ayir", ar: "أيير", fr: "Ayir", aliases: ["أيير", "ayir"], population: 30870 },
  { slug: "oulad-berhil", ar: "أولاد برحيل", fr: "Oulad Berhil", aliases: ["أولاد برحيل", "oulad berhil"], population: 30330 },
  { slug: "sidi-moussa-majdoub", ar: "سيدي موسى المجذوب", fr: "Sidi Moussa Majdoub", aliases: ["سيدي موسى المجذوب", "sidi moussa majdoub"], population: 30254 },
  { slug: "lbir-jdid", ar: "البئر الجديد", fr: "Lbir Jdid", aliases: ["البئر الجديد", "lbir jdid"], population: 30247 },
  { slug: "dar-ould-zidouh", ar: "دار ولد زيدوح", fr: "Dar Ould Zidouh", aliases: ["دار ولد زيدوح", "dar ould zidouh"], population: 30114 },
  { slug: "bouarfa", ar: "بوعرفة", fr: "Bouarfa", aliases: ["بوعرفة", "bouarfa"], population: 30068 },
  { slug: "mhaya", ar: "لمحايا", fr: "M'haya", aliases: ["لمحايا", "mhaya"], population: 30060 },
  { slug: "ouled-zmam", ar: "أولاد زمام", fr: "Ouled Zmam", aliases: ["أولاد زمام", "ouled zmam"], population: 30039 },
  { slug: "hrara", ar: "الحرارة", fr: "Hrara", aliases: ["الحرارة", "hrara"], population: 30025 },
  { slug: "mediouna", ar: "مديونة", fr: "Mediouna", aliases: ["مديونة", "mediouna"], population: 29972 },
  { slug: "bab-taza", ar: "باب تازة", fr: "Bab Taza", aliases: ["باب تازة", "bab taza"], population: 29895 },
  { slug: "selouane", ar: "سلوان", fr: "Selouane", aliases: ["سلوان", "selouane"], population: 29628 },
  { slug: "fritissa", ar: "فريطيسة", fr: "Fritissa", aliases: ["فريطيسة", "fritissa"], population: 29594 },
  { slug: "zemrane-charqia", ar: "زمران الشرقية", fr: "Zemrane Charqia", aliases: ["زمران الشرقية", "zemrane charqia"], population: 29569 },
  { slug: "sidi-allal-el-bahraoui", ar: "سيدي علال البحراوي", fr: "Sidi Allal El Bahraoui", aliases: ["سيدي علال البحراوي", "sidi allal el bahraoui"], population: 29147 },
  { slug: "el-mansouria", ar: "المنصورية", fr: "El Mansouria", aliases: ["المنصورية", "el mansouria"], population: 29139 },
  { slug: "arfoud", ar: "أرفود", fr: "Arfoud", aliases: ["أرفود", "arfoud"], population: 28912 },
  { slug: "el-marsa", ar: "المرسى", fr: "El Marsa", aliases: ["المرسى", "el marsa"], population: 28848 },
  { slug: "sabaa-aiyoun", ar: "سبع عيون", fr: "Sabaa Aiyoun", aliases: ["سبع عيون", "sabaa aiyoun"], population: 28736 },
  { slug: "beni-malek", ar: "بني مالك", fr: "Beni Malek", aliases: ["بني مالك", "beni malek"], population: 28711 },
  { slug: "ghmat", ar: "أغمات", fr: "Ghmat", aliases: ["أغمات", "ghmat"], population: 28674 },
  { slug: "tahla", ar: "تاهلة", fr: "Tahla", aliases: ["تاهلة", "tahla"], population: 28612 },
  { slug: "krifate", ar: "الكريفات", fr: "Krifate", aliases: ["الكريفات", "krifate"], population: 28601 },
  { slug: "ain-cheggag", ar: "عين الشقاق", fr: "Ain Cheggag", aliases: ["عين الشقاق", "ain cheggag"], population: 28584 },
  { slug: "er-rich", ar: "الريش", fr: "Er-rich", aliases: ["الريش", "er-rich", "er rich"], population: 28462 },
  { slug: "missour", ar: "ميسور", fr: "Missour", aliases: ["ميسور", "missour"], population: 28408 },
  { slug: "saniat-berguig", ar: "سانية بركيك", fr: "Saniat Berguig", aliases: ["سانية بركيك", "saniat berguig"], population: 28361 },
  { slug: "dkhissa", ar: "دخيسة", fr: "Dkhissa", aliases: ["دخيسة", "dkhissa"], population: 28296 },
  { slug: "sefsaf", ar: "الصفصاف", fr: "Sefsaf", aliases: ["الصفصاف", "sefsaf"], population: 28106 },
  { slug: "ouled-ghanem", ar: "أولاد غانم", fr: "Ouled Ghanem", aliases: ["أولاد غانم", "ouled ghanem"], population: 27895 },
  { slug: "oulad-hassoune", ar: "أولاد حسون", fr: "Oulad Hassoune", aliases: ["أولاد حسون", "oulad hassoune"], population: 27314 },
  { slug: "hjar-ennhal", ar: "حجر النحل", fr: "Hjar Ennhal", aliases: ["حجر النحل", "hjar ennhal"], population: 27204 },
  { slug: "sid-lmokhtar", ar: "سيدي المختار", fr: "Sid L'mokhtar", aliases: ["سيدي المختار", "sid lmokhtar"], population: 27083 },
  { slug: "lamzoudia", ar: "لمزوضية", fr: "Lamzoudia", aliases: ["لمزوضية", "lamzoudia"], population: 27004 },
  { slug: "toulal", ar: "تولال", fr: "Toulal", aliases: ["تولال", "toulal"], population: 26970 },
  { slug: "nouirate", ar: "النويرات", fr: "Nouirate", aliases: ["النويرات", "nouirate"], population: 26833 },
  { slug: "sebaa-rouadi", ar: "سبع رواضي", fr: "Sebaa Rouadi", aliases: ["سبع رواضي", "sebaa rouadi"], population: 26750 },
  { slug: "ouled-nacer", ar: "أولاد ناصر", fr: "Ouled Nacer", aliases: ["أولاد ناصر", "ouled nacer"], population: 26733 },
  { slug: "echemmaia", ar: "الشماعية", fr: "Echemmaia", aliases: ["الشماعية", "echemmaia"], population: 26547 },
  { slug: "mers-el-kheir", ar: "مرس الخير", fr: "Mers El Kheir", aliases: ["مرس الخير", "mers el kheir"], population: 26544 },
  { slug: "taddart", ar: "تدارت", fr: "Taddart", aliases: ["تدارت", "taddart"], population: 26540 },
  { slug: "ouaoula", ar: "أوعولة", fr: "Ouaoula", aliases: ["أوعولة", "ouaoula"], population: 26410 },
  { slug: "khnichet", ar: "خنيشات", fr: "Khnichet", aliases: ["خنيشات", "khnichet"], population: 26246 },
  { slug: "laghdira", ar: "الغديرة", fr: "Laghdira", aliases: ["الغديرة", "laghdira"], population: 26192 },
  { slug: "mettouh", ar: "مطوح", fr: "Mettouh", aliases: ["مطوح", "mettouh"], population: 26075 },
  { slug: "oulad-settout", ar: "أولاد ستوت", fr: "Oulad Settout", aliases: ["أولاد ستوت", "oulad settout"], population: 26052 },
  { slug: "sidi-abed", ar: "سيدي عابد", fr: "Sidi Abed", aliases: ["سيدي عابد", "sidi abed"], population: 25935 },
];

/* المدن الكبار — للفوتر وخريطة الموقع. 220 رابط فالفوتر ماكيخدم
   حتى شي حد، و220 صفحة مدينة خاوية فSitemap كتضرّ أكثر ما تنفع. */
export const TOP_CITIES = CITIES.slice(0, 24);

export const cityBySlug = (slug: string) => CITIES.find((c) => c.slug === slug);
export const cityName = (slug: string) => cityBySlug(slug)?.ar ?? slug;
