-- ============================================================
-- كتالوج المركبات — ماركات وموديلات كتّباع فالمغرب
--
-- مولّد من: morocco-cars-2026.xlsx
-- المصدر: Moteur.ma / Ovoiture (كتالوج السيارات الجديدة 2026)
--
-- مرجع فقط: ماكاين لا أثمنة لا كيلومتراج لا بائعين. الإعلانات
-- الحقيقية كتجي من الناس.
--
-- كيتعاود تشغيلو بلا مشكل: ON CONFLICT كيحيّن اللي كاين.
-- الاستعمال: Neon SQL Editor → الصق → Run
-- ============================================================

INSERT INTO catalog_brands (make, kind, country, parent_group) VALUES
  ('Abarth', 'car', 'Italy', 'Stellantis'),
  ('Alfa Romeo', 'car', 'Italy', 'Stellantis'),
  ('Alpine', 'car', 'France', 'Renault Group'),
  ('Aston Martin', 'car', 'United Kingdom', 'Aston Martin Lagonda'),
  ('Audi', 'car', 'Germany', 'Volkswagen Group'),
  ('BAIC', 'car', 'China', 'BAIC Group'),
  ('BMW', 'car', 'Germany', 'BMW Group'),
  ('BYD', 'car', 'China', 'BYD'),
  ('Bentley', 'car', 'United Kingdom', 'Volkswagen Group'),
  ('Changan', 'car', 'China', 'Changan Automobile'),
  ('Chery', 'car', 'China', 'Chery Group'),
  ('Chevrolet', 'car', 'United States', 'General Motors'),
  ('Citroën', 'car', 'France', 'Stellantis'),
  ('Cupra', 'car', 'Spain', 'Volkswagen Group'),
  ('DEEPAL', 'car', 'China', 'Changan Automobile'),
  ('DFSK', 'car', 'China', 'Seres Group'),
  ('DS', 'car', 'France', 'Stellantis'),
  ('Dacia', 'car', 'Romania', 'Renault Group'),
  ('Dongfeng', 'car', 'China', 'Dongfeng Motor'),
  ('EXEED', 'car', 'China', 'Chery Group'),
  ('Ferrari', 'car', 'Italy', 'Ferrari'),
  ('Fiat', 'car', 'Italy', 'Stellantis'),
  ('Ford', 'car', 'United States', 'Ford Motor Company'),
  ('Foton', 'car', 'China', 'BAIC/Foton'),
  ('GAZ', 'car', 'Russia', 'GAZ Group'),
  ('GWM', 'car', 'China', 'Great Wall Motor'),
  ('Geely', 'car', 'China', 'Geely Holding'),
  ('Honda', 'car', 'Japan', 'Honda Motor'),
  ('Hyundai', 'car', 'South Korea', 'Hyundai Motor Group'),
  ('Isuzu', 'car', 'Japan', 'Isuzu Motors'),
  ('JAC', 'car', 'China', 'JAC Group'),
  ('Jaecoo', 'car', 'China', 'Chery Group'),
  ('Jaguar', 'car', 'United Kingdom', 'JLR'),
  ('Jeep', 'car', 'United States', 'Stellantis'),
  ('Jetour', 'car', 'China', 'Chery Group'),
  ('KGM', 'car', 'South Korea', 'KG Mobility'),
  ('Kia', 'car', 'South Korea', 'Hyundai Motor Group'),
  ('Land Rover', 'car', 'United Kingdom', 'JLR'),
  ('Leapmotor', 'car', 'China', 'Leapmotor / Stellantis'),
  ('Lexus', 'car', 'Japan', 'Toyota Group'),
  ('Lynk & Co', 'car', 'China', 'Geely Holding'),
  ('MG', 'car', 'China/UK heritage', 'SAIC Motor'),
  ('Mahindra', 'car', 'India', 'Mahindra Group'),
  ('Maserati', 'car', 'Italy', 'Stellantis'),
  ('Mazda', 'car', 'Japan', 'Mazda Motor'),
  ('Mercedes', 'car', 'Germany', 'Mercedes-Benz Group'),
  ('Mini', 'car', 'United Kingdom', 'BMW Group'),
  ('Mitsubishi', 'car', 'Japan', 'Mitsubishi Motors'),
  ('Neo Motors', 'car', 'Morocco', 'Neo Motors'),
  ('Nissan', 'car', 'Japan', 'Nissan Motor'),
  ('Omoda', 'car', 'China', 'Chery Group'),
  ('Opel', 'car', 'Germany', 'Stellantis'),
  ('Peugeot', 'car', 'France', 'Stellantis'),
  ('Porsche', 'car', 'Germany', 'Volkswagen Group'),
  ('ROX', 'car', 'China', 'ROX Motor'),
  ('Renault', 'car', 'France', 'Renault Group'),
  ('Seat', 'car', 'Spain', 'Volkswagen Group'),
  ('Seres', 'car', 'China', 'Seres Group'),
  ('Skoda', 'car', 'Czech Republic', 'Volkswagen Group'),
  ('Smart', 'car', 'Germany/China', 'Mercedes-Benz / Geely'),
  ('Soueast', 'car', 'China', 'Chery Group'),
  ('SsangYong', 'car', 'South Korea', 'KG Mobility'),
  ('Suzuki', 'car', 'Japan', 'Suzuki Motor'),
  ('Tata', 'car', 'India', 'Tata Motors'),
  ('Tesla', 'car', 'United States', 'Tesla'),
  ('Toyota', 'car', 'Japan', 'Toyota Group'),
  ('Volkswagen', 'car', 'Germany', 'Volkswagen Group'),
  ('Volvo', 'car', 'Sweden', 'Geely Holding'),
  ('XPENG', 'car', 'China', 'XPENG'),
  ('Zeekr', 'car', 'China', 'Geely Holding'),
  ('BMW', 'moto', NULL, NULL),
  ('Bajaj', 'moto', NULL, NULL),
  ('Benelli', 'moto', NULL, NULL),
  ('Docker', 'moto', NULL, NULL),
  ('Haojue', 'moto', NULL, NULL),
  ('Harley-Davidson', 'moto', NULL, NULL),
  ('Honda', 'moto', NULL, NULL),
  ('KTM', 'moto', NULL, NULL),
  ('Kawasaki', 'moto', NULL, NULL),
  ('Kymco', 'moto', NULL, NULL),
  ('MBK', 'moto', NULL, NULL),
  ('Peugeot', 'moto', NULL, NULL),
  ('Royal Enfield', 'moto', NULL, NULL),
  ('SYM', 'moto', NULL, NULL),
  ('Suzuki', 'moto', NULL, NULL),
  ('Vespa', 'moto', NULL, NULL),
  ('Yamaha', 'moto', NULL, NULL)
ON CONFLICT (make, kind) DO UPDATE
  SET country = EXCLUDED.country, parent_group = EXCLUDED.parent_group;

INSERT INTO catalog_models (kind, make, model, body) VALUES
  ('car', 'Abarth', '500', NULL),
  ('car', 'Abarth', '500e', NULL),
  ('car', 'Abarth', '595', NULL),
  ('car', 'Abarth', '695', NULL),
  ('car', 'Alfa Romeo', 'Giulia', NULL),
  ('car', 'Alfa Romeo', 'Junior', NULL),
  ('car', 'Alfa Romeo', 'Stelvio', NULL),
  ('car', 'Alfa Romeo', 'Tonale', NULL),
  ('car', 'Alpine', 'A110', NULL),
  ('car', 'Alpine', 'A290', NULL),
  ('car', 'Alpine', 'A390', NULL),
  ('car', 'Aston Martin', 'DB12', NULL),
  ('car', 'Aston Martin', 'DBX', NULL),
  ('car', 'Aston Martin', 'Vanquish', NULL),
  ('car', 'Aston Martin', 'Vantage', NULL),
  ('car', 'Audi', 'A1', NULL),
  ('car', 'Audi', 'A3', 'citadine'),
  ('car', 'Audi', 'A4', 'berline'),
  ('car', 'Audi', 'A5', NULL),
  ('car', 'Audi', 'A6', NULL),
  ('car', 'Audi', 'A7', NULL),
  ('car', 'Audi', 'A8', NULL),
  ('car', 'Audi', 'Q2', NULL),
  ('car', 'Audi', 'Q3', 'suv'),
  ('car', 'Audi', 'Q4 e-tron', NULL),
  ('car', 'Audi', 'Q5', NULL),
  ('car', 'Audi', 'Q6 e-tron', NULL),
  ('car', 'Audi', 'Q7', NULL),
  ('car', 'Audi', 'Q8', NULL),
  ('car', 'Audi', 'e-tron', NULL),
  ('car', 'BAIC', 'BJ30', NULL),
  ('car', 'BAIC', 'BJ30e', NULL),
  ('car', 'BAIC', 'BJ40', NULL),
  ('car', 'BAIC', 'BJ60', NULL),
  ('car', 'BAIC', 'BJ80', NULL),
  ('car', 'BAIC', 'X35', NULL),
  ('car', 'BAIC', 'X55', NULL),
  ('car', 'BAIC', 'X7', NULL),
  ('car', 'BMW', '1 Series', NULL),
  ('car', 'BMW', '2 Series', NULL),
  ('car', 'BMW', '3 Series', NULL),
  ('car', 'BMW', '4 Series', NULL),
  ('car', 'BMW', '5 Series', NULL),
  ('car', 'BMW', '7 Series', NULL),
  ('car', 'BMW', '8 Series', NULL),
  ('car', 'BMW', 'Série 1', 'citadine'),
  ('car', 'BMW', 'Série 3', 'berline'),
  ('car', 'BMW', 'X1', 'suv'),
  ('car', 'BMW', 'X2', NULL),
  ('car', 'BMW', 'X3', NULL),
  ('car', 'BMW', 'X4', NULL),
  ('car', 'BMW', 'X5', NULL),
  ('car', 'BMW', 'X6', NULL),
  ('car', 'BMW', 'X7', NULL),
  ('car', 'BMW', 'Z4', NULL),
  ('car', 'BMW', 'i4', NULL),
  ('car', 'BMW', 'i5', NULL),
  ('car', 'BMW', 'i7', NULL),
  ('car', 'BMW', 'iX', NULL),
  ('car', 'BYD', 'Atto 3', NULL),
  ('car', 'BYD', 'Denza D9', NULL),
  ('car', 'BYD', 'Dolphin', NULL),
  ('car', 'BYD', 'Han', NULL),
  ('car', 'BYD', 'Qin Plus', NULL),
  ('car', 'BYD', 'Seagull', NULL),
  ('car', 'BYD', 'Seal', NULL),
  ('car', 'BYD', 'Seal U', NULL),
  ('car', 'BYD', 'Sealion 7', NULL),
  ('car', 'BYD', 'Shark 6', NULL),
  ('car', 'BYD', 'Song Plus', NULL),
  ('car', 'BYD', 'Tang', NULL),
  ('car', 'Bentley', 'Bentayga', NULL),
  ('car', 'Bentley', 'Continental GT', NULL),
  ('car', 'Bentley', 'Flying Spur', NULL),
  ('car', 'Changan', 'Alsvin', NULL),
  ('car', 'Changan', 'CS35 Plus', NULL),
  ('car', 'Changan', 'CS55 Plus', NULL),
  ('car', 'Changan', 'CS75 Plus', NULL),
  ('car', 'Changan', 'CS85', NULL),
  ('car', 'Changan', 'Hunter', NULL),
  ('car', 'Changan', 'UNI-K', NULL),
  ('car', 'Changan', 'UNI-T', NULL),
  ('car', 'Changan', 'UNI-V', NULL),
  ('car', 'Chery', 'Arrizo 5', NULL),
  ('car', 'Chery', 'Arrizo 8', NULL),
  ('car', 'Chery', 'Tiggo 2 Pro', NULL),
  ('car', 'Chery', 'Tiggo 4 Pro', NULL),
  ('car', 'Chery', 'Tiggo 7 Pro', NULL),
  ('car', 'Chery', 'Tiggo 8 Pro', NULL),
  ('car', 'Chery', 'Tiggo 8 Pro Max', NULL),
  ('car', 'Chevrolet', 'Captiva', NULL),
  ('car', 'Chevrolet', 'Equinox', NULL),
  ('car', 'Chevrolet', 'Groove', NULL),
  ('car', 'Chevrolet', 'Spark', 'citadine'),
  ('car', 'Chevrolet', 'Tahoe', NULL),
  ('car', 'Chevrolet', 'Tracker', NULL),
  ('car', 'Chevrolet', 'Trax', NULL),
  ('car', 'Citroën', 'Ami', NULL),
  ('car', 'Citroën', 'Berlingo', NULL),
  ('car', 'Citroën', 'C-Elysée', 'berline'),
  ('car', 'Citroën', 'C3', 'citadine'),
  ('car', 'Citroën', 'C3 Aircross', NULL),
  ('car', 'Citroën', 'C4', NULL),
  ('car', 'Citroën', 'C4 X', NULL),
  ('car', 'Citroën', 'C5 Aircross', NULL),
  ('car', 'Citroën', 'Jumpy', NULL),
  ('car', 'Cupra', 'Ateca', NULL),
  ('car', 'Cupra', 'Born', NULL),
  ('car', 'Cupra', 'Formentor', NULL),
  ('car', 'Cupra', 'Leon', NULL),
  ('car', 'Cupra', 'Tavascan', NULL),
  ('car', 'Cupra', 'Terramar', NULL),
  ('car', 'DEEPAL', 'L07', NULL),
  ('car', 'DEEPAL', 'S05', NULL),
  ('car', 'DEEPAL', 'S07', NULL),
  ('car', 'DEEPAL', 'SL03', NULL),
  ('car', 'DFSK', 'C31', NULL),
  ('car', 'DFSK', 'C32', NULL),
  ('car', 'DFSK', 'E5', NULL),
  ('car', 'DFSK', 'Glory 500', NULL),
  ('car', 'DFSK', 'Glory 580', NULL),
  ('car', 'DFSK', 'K01h', NULL),
  ('car', 'DFSK', 'K01s', NULL),
  ('car', 'DS', 'DS 3', NULL),
  ('car', 'DS', 'DS 4', NULL),
  ('car', 'DS', 'DS 7', NULL),
  ('car', 'DS', 'DS 9', NULL),
  ('car', 'Dacia', 'Bigster', NULL),
  ('car', 'Dacia', 'Dokker', 'utilitaire'),
  ('car', 'Dacia', 'Duster', 'suv'),
  ('car', 'Dacia', 'Jogger', NULL),
  ('car', 'Dacia', 'Lodgy', 'break'),
  ('car', 'Dacia', 'Logan', 'berline'),
  ('car', 'Dacia', 'Sandero', 'citadine'),
  ('car', 'Dacia', 'Sandero Stepway', NULL),
  ('car', 'Dacia', 'Spring', 'citadine'),
  ('car', 'Dongfeng', 'Aeolus Yixuan', NULL),
  ('car', 'Dongfeng', 'Box', NULL),
  ('car', 'Dongfeng', 'Huge', NULL),
  ('car', 'Dongfeng', 'Mage', NULL),
  ('car', 'Dongfeng', 'Shine', NULL),
  ('car', 'Dongfeng', 'T5 EVO', NULL),
  ('car', 'EXEED', 'LX', NULL),
  ('car', 'EXEED', 'RX', NULL),
  ('car', 'EXEED', 'TXL', NULL),
  ('car', 'EXEED', 'VX', NULL),
  ('car', 'EXEED', 'VX PHEV', NULL),
  ('car', 'Ferrari', '12Cilindri', NULL),
  ('car', 'Ferrari', '296 GTB', NULL),
  ('car', 'Ferrari', '296 GTS', NULL),
  ('car', 'Ferrari', 'Purosangue', NULL),
  ('car', 'Ferrari', 'Roma', NULL),
  ('car', 'Ferrari', 'SF90 Spider', NULL),
  ('car', 'Ferrari', 'SF90 Stradale', NULL),
  ('car', 'Fiat', '500', NULL),
  ('car', 'Fiat', '500X', NULL),
  ('car', 'Fiat', '500e', NULL),
  ('car', 'Fiat', 'Doblo', NULL),
  ('car', 'Fiat', 'Ducato', NULL),
  ('car', 'Fiat', 'Grande Panda', NULL),
  ('car', 'Fiat', 'Panda', NULL),
  ('car', 'Fiat', 'Punto', 'citadine'),
  ('car', 'Fiat', 'Tipo', 'berline'),
  ('car', 'Fiat', 'Topolino', NULL),
  ('car', 'Ford', 'Bronco', NULL),
  ('car', 'Ford', 'Everest', NULL),
  ('car', 'Ford', 'Fiesta', 'citadine'),
  ('car', 'Ford', 'Focus', 'citadine'),
  ('car', 'Ford', 'Kuga', NULL),
  ('car', 'Ford', 'Mondeo', NULL),
  ('car', 'Ford', 'Mustang', NULL),
  ('car', 'Ford', 'Puma', NULL),
  ('car', 'Ford', 'Ranger', 'utilitaire'),
  ('car', 'Ford', 'Tourneo Custom', NULL),
  ('car', 'Ford', 'Transit', NULL),
  ('car', 'Foton', 'Aumark', NULL),
  ('car', 'Foton', 'TM', NULL),
  ('car', 'Foton', 'Toano', NULL),
  ('car', 'Foton', 'Tunland', NULL),
  ('car', 'Foton', 'Tunland G7', NULL),
  ('car', 'GAZ', 'Gazelle Next', NULL),
  ('car', 'GAZ', 'Sobol', NULL),
  ('car', 'GAZ', 'Ural Next', NULL),
  ('car', 'GWM', 'Haval H6', NULL),
  ('car', 'GWM', 'Haval H9', NULL),
  ('car', 'GWM', 'Haval Jolion', NULL),
  ('car', 'GWM', 'Poer', NULL),
  ('car', 'GWM', 'Poer KingKong', NULL),
  ('car', 'GWM', 'Tank 300', NULL),
  ('car', 'GWM', 'Tank 500', NULL),
  ('car', 'Geely', 'Atlas', NULL),
  ('car', 'Geely', 'Coolray', NULL),
  ('car', 'Geely', 'Emgrand', NULL),
  ('car', 'Geely', 'GX3 Pro', NULL),
  ('car', 'Geely', 'Geometry C', NULL),
  ('car', 'Geely', 'Monjaro', NULL),
  ('car', 'Geely', 'Tugella', NULL),
  ('car', 'Honda', 'Accord', NULL),
  ('car', 'Honda', 'CR-V', NULL),
  ('car', 'Honda', 'City', NULL),
  ('car', 'Honda', 'Civic', NULL),
  ('car', 'Honda', 'HR-V', NULL),
  ('car', 'Honda', 'ZR-V', NULL),
  ('car', 'Honda', 'e:Ny1', NULL),
  ('car', 'Hyundai', 'Accent', 'berline'),
  ('car', 'Hyundai', 'Bayon', NULL),
  ('car', 'Hyundai', 'Elantra', NULL),
  ('car', 'Hyundai', 'Ioniq 5', NULL),
  ('car', 'Hyundai', 'Ioniq 6', NULL),
  ('car', 'Hyundai', 'Kona', 'suv'),
  ('car', 'Hyundai', 'Santa Fe', NULL),
  ('car', 'Hyundai', 'Staria', NULL),
  ('car', 'Hyundai', 'Tucson', 'suv'),
  ('car', 'Hyundai', 'i10', 'citadine'),
  ('car', 'Hyundai', 'i20', 'citadine'),
  ('car', 'Hyundai', 'i30', NULL),
  ('car', 'Isuzu', 'D-Max', 'utilitaire'),
  ('car', 'Isuzu', 'MU-X', NULL),
  ('car', 'Isuzu', 'N-Series', NULL),
  ('car', 'JAC', 'JS2', NULL),
  ('car', 'JAC', 'JS3', NULL),
  ('car', 'JAC', 'JS4', NULL),
  ('car', 'JAC', 'JS6', NULL),
  ('car', 'JAC', 'T8', NULL),
  ('car', 'JAC', 'T9', NULL),
  ('car', 'Jaecoo', 'J5', NULL),
  ('car', 'Jaecoo', 'J7', NULL),
  ('car', 'Jaecoo', 'J7 PHEV', NULL),
  ('car', 'Jaecoo', 'J8', NULL),
  ('car', 'Jaecoo', 'J8 PHEV', NULL),
  ('car', 'Jaguar', 'E-Pace', NULL),
  ('car', 'Jaguar', 'F-Pace', NULL),
  ('car', 'Jaguar', 'F-Type', NULL),
  ('car', 'Jaguar', 'I-Pace', NULL),
  ('car', 'Jeep', 'Avenger', NULL),
  ('car', 'Jeep', 'Compass', 'suv'),
  ('car', 'Jeep', 'Grand Cherokee', NULL),
  ('car', 'Jeep', 'Renegade', NULL),
  ('car', 'Jeep', 'Wrangler', NULL),
  ('car', 'Jetour', 'Dashing', NULL),
  ('car', 'Jetour', 'T2', NULL),
  ('car', 'Jetour', 'Traveller', NULL),
  ('car', 'Jetour', 'X50', NULL),
  ('car', 'Jetour', 'X70', NULL),
  ('car', 'Jetour', 'X70 Plus', NULL),
  ('car', 'Jetour', 'X90 Plus', NULL),
  ('car', 'KGM', 'Korando', NULL),
  ('car', 'KGM', 'Musso', NULL),
  ('car', 'KGM', 'Musso Grand', NULL),
  ('car', 'KGM', 'Rexton', NULL),
  ('car', 'KGM', 'Tivoli', NULL),
  ('car', 'KGM', 'Torres', NULL),
  ('car', 'KGM', 'Torres EVX', NULL),
  ('car', 'Kia', 'Carnival', NULL),
  ('car', 'Kia', 'EV3', NULL),
  ('car', 'Kia', 'EV6', NULL),
  ('car', 'Kia', 'EV9', NULL),
  ('car', 'Kia', 'K3', NULL),
  ('car', 'Kia', 'K5', NULL),
  ('car', 'Kia', 'Niro', NULL),
  ('car', 'Kia', 'Picanto', 'citadine'),
  ('car', 'Kia', 'Rio', 'citadine'),
  ('car', 'Kia', 'Seltos', NULL),
  ('car', 'Kia', 'Sorento', NULL),
  ('car', 'Kia', 'Sportage', 'suv'),
  ('car', 'Land Rover', 'Defender', NULL),
  ('car', 'Land Rover', 'Discovery', NULL),
  ('car', 'Land Rover', 'Discovery Sport', NULL),
  ('car', 'Land Rover', 'Range Rover', NULL),
  ('car', 'Land Rover', 'Range Rover Evoque', 'suv'),
  ('car', 'Land Rover', 'Range Rover Sport', NULL),
  ('car', 'Land Rover', 'Range Rover Velar', NULL),
  ('car', 'Leapmotor', 'C10', NULL),
  ('car', 'Leapmotor', 'C11', NULL),
  ('car', 'Leapmotor', 'C16', NULL),
  ('car', 'Leapmotor', 'T03', NULL),
  ('car', 'Lexus', 'ES', NULL),
  ('car', 'Lexus', 'LBX', NULL),
  ('car', 'Lexus', 'LS', NULL),
  ('car', 'Lexus', 'LX', NULL),
  ('car', 'Lexus', 'NX', NULL),
  ('car', 'Lexus', 'RX', NULL),
  ('car', 'Lexus', 'UX', NULL),
  ('car', 'Lynk & Co', '01', NULL),
  ('car', 'Lynk & Co', '02', NULL),
  ('car', 'Lynk & Co', '03', NULL),
  ('car', 'Lynk & Co', '05', NULL),
  ('car', 'Lynk & Co', '06', NULL),
  ('car', 'Lynk & Co', '09', NULL),
  ('car', 'MG', 'Cyberster', NULL),
  ('car', 'MG', 'MG GT', NULL),
  ('car', 'MG', 'MG HS', NULL),
  ('car', 'MG', 'MG ZS', NULL),
  ('car', 'MG', 'MG3', NULL),
  ('car', 'MG', 'MG4', NULL),
  ('car', 'MG', 'MG5', NULL),
  ('car', 'MG', 'Marvel R', NULL),
  ('car', 'Mahindra', 'PIK-UP', NULL),
  ('car', 'Mahindra', 'Scorpio', NULL),
  ('car', 'Mahindra', 'Thar', NULL),
  ('car', 'Mahindra', 'XUV300', NULL),
  ('car', 'Mahindra', 'XUV700', NULL),
  ('car', 'Maserati', 'GranCabrio', NULL),
  ('car', 'Maserati', 'GranTurismo', NULL),
  ('car', 'Maserati', 'Grecale', NULL),
  ('car', 'Maserati', 'Levante', NULL),
  ('car', 'Maserati', 'MC20', NULL),
  ('car', 'Mazda', 'CX-3', NULL),
  ('car', 'Mazda', 'CX-30', NULL),
  ('car', 'Mazda', 'CX-5', NULL),
  ('car', 'Mazda', 'CX-60', NULL),
  ('car', 'Mazda', 'CX-80', NULL),
  ('car', 'Mazda', 'MX-5', NULL),
  ('car', 'Mazda', 'Mazda 2', NULL),
  ('car', 'Mazda', 'Mazda 3', NULL),
  ('car', 'Mercedes', 'A-Class', NULL),
  ('car', 'Mercedes', 'B-Class', NULL),
  ('car', 'Mercedes', 'C-Class', NULL),
  ('car', 'Mercedes', 'CLA', NULL),
  ('car', 'Mercedes', 'CLE', NULL),
  ('car', 'Mercedes', 'Classe A', 'citadine'),
  ('car', 'Mercedes', 'Classe C', 'berline'),
  ('car', 'Mercedes', 'Classe E', 'berline'),
  ('car', 'Mercedes', 'E-Class', NULL),
  ('car', 'Mercedes', 'EQA', NULL),
  ('car', 'Mercedes', 'EQB', NULL),
  ('car', 'Mercedes', 'EQE', NULL),
  ('car', 'Mercedes', 'EQS', NULL),
  ('car', 'Mercedes', 'G-Class', NULL),
  ('car', 'Mercedes', 'GLA', NULL),
  ('car', 'Mercedes', 'GLB', NULL),
  ('car', 'Mercedes', 'GLC', NULL),
  ('car', 'Mercedes', 'GLE', NULL),
  ('car', 'Mercedes', 'GLS', NULL),
  ('car', 'Mercedes', 'S-Class', NULL),
  ('car', 'Mini', 'Aceman', NULL),
  ('car', 'Mini', 'Clubman', NULL),
  ('car', 'Mini', 'Cooper 3 Door', NULL),
  ('car', 'Mini', 'Cooper 5 Door', NULL),
  ('car', 'Mini', 'Cooper Convertible', NULL),
  ('car', 'Mini', 'Countryman', NULL),
  ('car', 'Mitsubishi', 'ASX', NULL),
  ('car', 'Mitsubishi', 'Eclipse Cross', NULL),
  ('car', 'Mitsubishi', 'L200', 'utilitaire'),
  ('car', 'Mitsubishi', 'Outlander', NULL),
  ('car', 'Mitsubishi', 'Pajero Sport', NULL),
  ('car', 'Neo Motors', 'Neo', NULL),
  ('car', 'Neo Motors', 'Neo City', NULL),
  ('car', 'Nissan', 'Ariya', NULL),
  ('car', 'Nissan', 'Juke', NULL),
  ('car', 'Nissan', 'Micra', 'citadine'),
  ('car', 'Nissan', 'Navara', NULL),
  ('car', 'Nissan', 'Qashqai', 'suv'),
  ('car', 'Nissan', 'X-Trail', NULL),
  ('car', 'Omoda', 'Omoda 5', NULL),
  ('car', 'Omoda', 'Omoda 7', NULL),
  ('car', 'Omoda', 'Omoda C5', NULL),
  ('car', 'Omoda', 'Omoda E5', NULL),
  ('car', 'Opel', 'Astra', NULL),
  ('car', 'Opel', 'Combo', NULL),
  ('car', 'Opel', 'Corsa', 'citadine'),
  ('car', 'Opel', 'Crossland', NULL),
  ('car', 'Opel', 'Grandland', NULL),
  ('car', 'Opel', 'Mokka', NULL),
  ('car', 'Opel', 'Vivaro', NULL),
  ('car', 'Opel', 'Zafira Life', NULL),
  ('car', 'Peugeot', '2008', NULL),
  ('car', 'Peugeot', '208', 'citadine'),
  ('car', 'Peugeot', '3008', 'suv'),
  ('car', 'Peugeot', '301', 'berline'),
  ('car', 'Peugeot', '308', NULL),
  ('car', 'Peugeot', '408', NULL),
  ('car', 'Peugeot', '5008', NULL),
  ('car', 'Peugeot', '508', NULL),
  ('car', 'Peugeot', 'Boxer', NULL),
  ('car', 'Peugeot', 'Expert', NULL),
  ('car', 'Peugeot', 'Partner', 'utilitaire'),
  ('car', 'Peugeot', 'Rifter', NULL),
  ('car', 'Peugeot', 'e-2008', NULL),
  ('car', 'Peugeot', 'e-208', NULL),
  ('car', 'Porsche', '718 Boxster', NULL),
  ('car', 'Porsche', '718 Cayman', NULL),
  ('car', 'Porsche', '911', NULL),
  ('car', 'Porsche', 'Cayenne', NULL),
  ('car', 'Porsche', 'Macan', NULL),
  ('car', 'Porsche', 'Panamera', NULL),
  ('car', 'Porsche', 'Taycan', NULL),
  ('car', 'ROX', '01', NULL),
  ('car', 'ROX', '01 REEV', NULL),
  ('car', 'Renault', 'Arkana', NULL),
  ('car', 'Renault', 'Austral', NULL),
  ('car', 'Renault', 'Captur', 'suv'),
  ('car', 'Renault', 'Clio', NULL),
  ('car', 'Renault', 'Clio 4', 'citadine'),
  ('car', 'Renault', 'Espace', NULL),
  ('car', 'Renault', 'Express', NULL),
  ('car', 'Renault', 'Kangoo', 'utilitaire'),
  ('car', 'Renault', 'Master', NULL),
  ('car', 'Renault', 'Megane', NULL),
  ('car', 'Renault', 'Mégane', 'berline'),
  ('car', 'Renault', 'Rafale', NULL),
  ('car', 'Renault', 'Symbol', 'berline'),
  ('car', 'Renault', 'Trafic', NULL),
  ('car', 'Renault', 'Zoe', 'citadine'),
  ('car', 'Seat', 'Arona', NULL),
  ('car', 'Seat', 'Ateca', NULL),
  ('car', 'Seat', 'Ibiza', 'citadine'),
  ('car', 'Seat', 'Leon', 'citadine'),
  ('car', 'Seat', 'Tarraco', NULL),
  ('car', 'Seres', '3', NULL),
  ('car', 'Seres', '5', NULL),
  ('car', 'Seres', '7', NULL),
  ('car', 'Seres', 'SF5', NULL),
  ('car', 'Skoda', 'Enyaq', NULL),
  ('car', 'Skoda', 'Fabia', 'citadine'),
  ('car', 'Skoda', 'Kamiq', NULL),
  ('car', 'Skoda', 'Karoq', NULL),
  ('car', 'Skoda', 'Kodiaq', NULL),
  ('car', 'Skoda', 'Octavia', 'berline'),
  ('car', 'Skoda', 'Scala', NULL),
  ('car', 'Skoda', 'Superb', NULL),
  ('car', 'Smart', '#1', NULL),
  ('car', 'Smart', '#3', NULL),
  ('car', 'Smart', '#5', NULL),
  ('car', 'Soueast', 'S06', NULL),
  ('car', 'Soueast', 'S07', NULL),
  ('car', 'Soueast', 'S09', NULL),
  ('car', 'SsangYong', 'Korando', NULL),
  ('car', 'SsangYong', 'Musso', NULL),
  ('car', 'SsangYong', 'Rexton', NULL),
  ('car', 'SsangYong', 'Tivoli', NULL),
  ('car', 'SsangYong', 'Torres', NULL),
  ('car', 'Suzuki', 'Across', NULL),
  ('car', 'Suzuki', 'Baleno', NULL),
  ('car', 'Suzuki', 'Dzire', NULL),
  ('car', 'Suzuki', 'Jimny', NULL),
  ('car', 'Suzuki', 'S-Cross', NULL),
  ('car', 'Suzuki', 'Swift', 'citadine'),
  ('car', 'Suzuki', 'Vitara', NULL),
  ('car', 'Tata', 'Harrier', NULL),
  ('car', 'Tata', 'Nexon', NULL),
  ('car', 'Tata', 'Punch', NULL),
  ('car', 'Tata', 'Safari', NULL),
  ('car', 'Tata', 'Super Ace', NULL),
  ('car', 'Tata', 'Tiago', NULL),
  ('car', 'Tata', 'Tigor', NULL),
  ('car', 'Tesla', 'Cybertruck', NULL),
  ('car', 'Tesla', 'Model 3', 'berline'),
  ('car', 'Tesla', 'Model S', NULL),
  ('car', 'Tesla', 'Model X', NULL),
  ('car', 'Tesla', 'Model Y', NULL),
  ('car', 'Toyota', 'Aygo X', NULL),
  ('car', 'Toyota', 'C-HR', NULL),
  ('car', 'Toyota', 'Camry', NULL),
  ('car', 'Toyota', 'Corolla', 'berline'),
  ('car', 'Toyota', 'Corolla Cross', NULL),
  ('car', 'Toyota', 'Fortuner', NULL),
  ('car', 'Toyota', 'Hilux', 'utilitaire'),
  ('car', 'Toyota', 'Land Cruiser', NULL),
  ('car', 'Toyota', 'Proace', NULL),
  ('car', 'Toyota', 'RAV4', NULL),
  ('car', 'Toyota', 'Yaris', 'citadine'),
  ('car', 'Toyota', 'Yaris Cross', NULL),
  ('car', 'Volkswagen', 'Arteon', NULL),
  ('car', 'Volkswagen', 'Caddy', 'utilitaire'),
  ('car', 'Volkswagen', 'Golf', NULL),
  ('car', 'Volkswagen', 'Golf 7', 'citadine'),
  ('car', 'Volkswagen', 'Golf 8', 'citadine'),
  ('car', 'Volkswagen', 'Golf Variant', NULL),
  ('car', 'Volkswagen', 'ID.3', NULL),
  ('car', 'Volkswagen', 'ID.4', NULL),
  ('car', 'Volkswagen', 'ID.5', NULL),
  ('car', 'Volkswagen', 'ID.7', NULL),
  ('car', 'Volkswagen', 'Passat', 'berline'),
  ('car', 'Volkswagen', 'Polo', 'citadine'),
  ('car', 'Volkswagen', 'T-Cross', NULL),
  ('car', 'Volkswagen', 'T-Roc', NULL),
  ('car', 'Volkswagen', 'Taigo', NULL),
  ('car', 'Volkswagen', 'Tiguan', 'suv'),
  ('car', 'Volkswagen', 'Touareg', NULL),
  ('car', 'Volkswagen', 'Transporter', NULL),
  ('car', 'Volvo', 'EC40', NULL),
  ('car', 'Volvo', 'EX30', NULL),
  ('car', 'Volvo', 'EX40', NULL),
  ('car', 'Volvo', 'EX90', NULL),
  ('car', 'Volvo', 'S60', NULL),
  ('car', 'Volvo', 'S90', NULL),
  ('car', 'Volvo', 'XC40', NULL),
  ('car', 'Volvo', 'XC60', NULL),
  ('car', 'Volvo', 'XC90', NULL),
  ('car', 'XPENG', 'G3', NULL),
  ('car', 'XPENG', 'G6', NULL),
  ('car', 'XPENG', 'G9', NULL),
  ('car', 'XPENG', 'P7', NULL),
  ('car', 'XPENG', 'P7+', NULL),
  ('car', 'XPENG', 'X9', NULL),
  ('car', 'Zeekr', '001', NULL),
  ('car', 'Zeekr', '007', NULL),
  ('car', 'Zeekr', '009', NULL),
  ('car', 'Zeekr', '7X', NULL),
  ('car', 'Zeekr', 'X', NULL),
  ('moto', 'BMW', 'F 850 GS', 'trail'),
  ('moto', 'BMW', 'R 1200 GS', 'trail'),
  ('moto', 'Bajaj', 'Boxer', 'roadster'),
  ('moto', 'Bajaj', 'Pulsar', 'roadster'),
  ('moto', 'Benelli', 'TRK 502', 'trail'),
  ('moto', 'Docker', 'Star', 'roadster'),
  ('moto', 'Haojue', 'DK 150', 'roadster'),
  ('moto', 'Harley-Davidson', 'Forty-Eight', 'custom'),
  ('moto', 'Harley-Davidson', 'Iron 883', 'custom'),
  ('moto', 'Honda', 'Africa Twin', 'trail'),
  ('moto', 'Honda', 'CB500X', 'trail'),
  ('moto', 'Honda', 'CBR 600RR', 'sportive'),
  ('moto', 'Honda', 'Forza 125', 'scooter'),
  ('moto', 'Honda', 'PCX 125', 'scooter'),
  ('moto', 'Honda', 'Transalp 750', 'trail'),
  ('moto', 'KTM', '790 Adventure', 'trail'),
  ('moto', 'KTM', 'Duke 390', 'roadster'),
  ('moto', 'Kawasaki', 'Ninja 650', 'sportive'),
  ('moto', 'Kawasaki', 'Z650', 'roadster'),
  ('moto', 'Kymco', 'Agility 125', 'scooter'),
  ('moto', 'MBK', 'Booster', 'scooter'),
  ('moto', 'Peugeot', 'Django', 'scooter'),
  ('moto', 'Peugeot', 'Kisbee', 'scooter'),
  ('moto', 'Royal Enfield', 'Classic 500', 'custom'),
  ('moto', 'Royal Enfield', 'Meteor 350', 'custom'),
  ('moto', 'SYM', 'Jet 14', 'scooter'),
  ('moto', 'SYM', 'Symphony 125', 'scooter'),
  ('moto', 'Suzuki', 'GSX-R 600', 'sportive'),
  ('moto', 'Vespa', 'Primavera 125', 'scooter'),
  ('moto', 'Yamaha', 'Aerox', 'scooter'),
  ('moto', 'Yamaha', 'MT-07', 'roadster'),
  ('moto', 'Yamaha', 'NMAX', 'scooter'),
  ('moto', 'Yamaha', 'R6', 'sportive'),
  ('moto', 'Yamaha', 'Tracer 700', 'trail'),
  ('moto', 'Yamaha', 'Ténéré 700', 'trail')
ON CONFLICT (kind, make, model) DO UPDATE
  SET body = COALESCE(EXCLUDED.body, catalog_models.body);

SELECT kind, count(*) AS n FROM catalog_models GROUP BY kind ORDER BY kind;
